# Generated by Django 6.0.7 on 2026-08-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_notification_followrequest'),
        ('posts', '0003_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow_request', 'Follow Request'), ('follow_accept', 'Follow Request Accepted'), ('new_follower', 'New Follower'), ('like', 'Like'), ('comment', 'Comment'), ('mention', 'Mention')], max_length=20),
        ),
    ]
